### ISSUE TITLE
Allow some way to configure immutable URLs

### ISSUE THREAD

**Issue by r0ckarong** [openSUSE/doc-ci#13]
I had a conversation with our beta program maintainer. I managed to screw up some branch that we communicated to customers. This means that we have to send a correction for the documentation URLs because the branch names (and thus URL) has changed.

Can we get some method of configuring susedoc.github.io to point to a configured branch of some document at a specific URL?

For example: 
We want some URL <resource>/caasp-deployment-guide that can be configured to always point to a configured branch. Then, in the background we can switch the branch this is pointing to that we want to expose to customers without changing the URL.

For example we release a beta and the branch is called `beta` the URL would be `https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html`. If we remove the `beta` branch this link will not work anymore.

If we could point some resource to <resource><configured_branch><document_url> this would give us a static URL with a configurable branch as the base.

**Comment by sknorr** [comment]
It would be a bit limiting to only have referrers to a single book, wouldn't it, though?

**Comment by sknorr** [comment]
I have added this now. In index-config.xml, you can now add "redirect" tags, I've added two for CaaSP:

```
  <redirect from="caasp-4-rn" to="caasp-release-notes/master/release-notes/html/"/>
  <redirect from="caasp-4-deploy" to="doc-caasp/master/caasp-deployment/html/"/>
```

They are accessible as https://susedoc.github.io/r/caasp-4-rn and https://susedoc.github.io/r/caasp-4-doc

I guess that is not exactly what you wanted but should work well enough.
