### ISSUE TITLE
Make .travis-check-docs obsolete

### ISSUE THREAD

**Issue by sknorr** [openSUSE/doc-ci#17]
Our story with validation has a few pitfalls and many of them hinge on .travis-check-docs. Generally, the goal should be to verify the following in the least amount of time:

- [x] 1. all MAIN files are valid in all used profiling variations.
- [ ] #47

* For (1.), using something like docserv-dchash might be an option. Ideally, the new tool would not have to build temporary DC files.
* For (2.) we'd probably need to build bigfiles and check for IDs in those.

Now, .travis-check-docs is just a list of DC files and it may or may not fulfill the purpose of accurately checking either of the above in any amount of time. It may be utterly failing, as all of this is completely dependent on humans properly or improperly updating the file.

**Comment by ghost** [comment]
GHA uses docserv-dchash. (1.) is solved.

**Comment by ghost** [comment]
To solve (2.) I think we should:

a. Make a secondary list of dependent documents to validate, if there are any.
b. Validate the list of secondary documents in the same runner that we validate the `DC-*-all` in, taking advantage of existing profiling etc. (We could also go via a bigfile and grep through it, but that probably would not yield gains while increasing the amount of code we need to maintain for our action.)

**Comment by ghost** [comment]
Opened #47 for the missing half, closing this.
