### ISSUE TITLE
translation branches always fail with the default settings

### ISSUE THREAD

**Issue by sknorr** [openSUSE/doc-ci#21]
Translation branches use subdirectories and can thus not be built automatically with the default settings. (You can work around this by listing all DC files including subdirs in .travis-check-docs.)

(report via @tbazant)

**Comment by ghost** [comment]
This has been fixed as part of the move to GitHub Actions: We use `find . -name 'DC-*'` to find all DC files within a repo rather than relying on the old `DC-*` glob.
