### ISSUE TITLE
What do we need the env.list file for?

### ISSUE THREAD

**Issue by sknorr** [openSUSE/doc-ci#22]
We are generating an env.list file with environment variables -- is there actually a need for this? Maybe we actually do, because we run a Docker container, but even then having a single `printenv | grep -P '^(TRAVIS_|ENCRYPTED_PRIVKEY_SECRET)' > env.list` command might be nicer than 6 individual echo commands.

**Comment by ghost** [comment]
No longer relevant with GHA.
