### ISSUE TITLE
Make susedoc.github.io paths more similar to doc.suse.com paths

### ISSUE THREAD

**Issue by sknorr** [openSUSE/doc-ci#23]
We have different path styles on susedoc.github.io and on doc.suse.com:

```
doc.s.c:  domain / [lang /] product / version / format   / document
sd.gh.io: domain /          product / branch  / document / format 
```

@mnapp remarks that it would be great if we could switch susedoc.github.io to the `format/document` style, to make it possible to reuse/redefine URL definitions from the beta page for production.

**Comment by sknorr** [comment]
@fsundermeyer / @taroth / @r0ckarong / @tbazant / @tomschr 

I made a quick/dirty fix for this. The fix involves breaking any deeplinks we have on the beta page. (But I still provide an index.html file to the book/article themselves.)
Is this an acceptable compromise or do you see this becoming an issue?

**Comment by r0ckarong** [comment]
The justification behind this is that we need to sometimes use URLs that do not exist yet in the final location (most often for release notes or beta). The release notes get packaged before we ship the documentation so I can not verify beforehand that the URLs are actually correct. If they DO exist on susedoc.github.io I can be pretty sure that the ID points to an existing anchor.

**Comment by sknorr** [comment]
Had no negative feedback.->Pushed.
