### ISSUE TITLE
Our SSH deploy keys are still associated with Sven's account

### ISSUE THREAD

**Issue by ghost** [openSUSE/doc-ci#35]
@lproven / @cwickert report seeing Sven instead of `SUSE Doc Team CI` as the author of our CI-created commits. ~~We should probably create an official doc-team bot account and create new deploy keys using it.~~ (Many of our current deploy keys were originally created for Travis anyway, so deauthing them may be a good idea in any case.)

Feed (via lproven):
![feed screenshot](https://user-images.githubusercontent.com/5476547/128356084-f6c4ce21-aed5-4892-b867-9ce3b36f380c.png)

This misleading committer information is apparently limited to the GitHub homepage's feed. This is the commit view of one such commit:
![commit screenshot](https://user-images.githubusercontent.com/5476547/128361745-ed5902ef-9a18-4508-b789-efb8dd56c7e3.png)

**Comment by ghost** [comment]
Update: We should probably switch to authenticating via a token rather than pass an SSH private key as the Actions secret: https://docs.github.com/en/actions/reference/authentication-in-a-workflow
[via @tomschr who already uses `${{ secrets.GITHUB_TOKEN }}` ]

**Comment by ghost** [comment]
Toms, that was a good idea, but it won't work; from the docs ~you~ I linked:
> The token's permissions are limited to the repository that contains your workflow.

We are _always_ pushing to different repo, e.g. from the context of `SUSE/doc-sle` we push to `SUSEdoc/doc-sle`. I think that we should keep that workflow as is, too, not just because we've been using it for a while and it's working, but also because we are doing a few slightly evil things to make sure that our publishing repos don't grow too large (namely we reset the entire repo every couple of revisions), that I don't think we should be performing in repos we actually host valuable source in. The other issue is related to usability--if we push to a branch of the docs repo itself, we could only host the overview page on `susedoc.github.io` but every link from that page would have to go to a different subdomain like `suse.github.io/doc-sle` or `suse-cloud.github.io/doc-cloud`.

I think we will need the "official" bot account after all.

**Comment by ghost** [comment]
@suse-docs-bot has taken over. Sorry, @svenseeberg.

**Comment by tomschr** [comment]
> Toms, that was a good idea, but it won't work; from the docs you linked:

That's a pity. It seems, this is not enough. Maybe using this specific GitHub Action [copy_file_to_another_repo_action](https://github.com/marketplace/actions/push-files-to-another-repository) would help? It's just an example, you can find similar Actions on the Marketplace. You need to set a secret of course, but that should be easy. Not sure if this helps...


> We are _always_ pushing to different repo, e.g. from the context of `SUSE/doc-sle` we push to `SUSEdoc/doc-sle`. I think that we should keep that workflow as is [...]

I agree, we shouldn't change the structure.

**Comment by ghost** [comment]
Well, I updated the entire config on Friday anyway, so it doesn't matter much anymore. :) 

> That's a pity. It seems, this is not enough. Maybe using this specific GitHub Action copy_file_to_another_repo_action would help? It's just an example, you can find similar Actions on the Marketplace. You need to set a secret of course, but that should be easy. Not sure if this helps...

As far as I understand this action, it needs a token that is connected to an actual (user) account, rather than allowing a token only connected to GitHub Actions. Meaning, we're back to needing a bot account with restricted rights, because (1) you don't want your name attached to automatic actions, and (2) you don't want to give automatic workflows all the rights that your normal user account has.

The model we now have is nicely locked down: Our bot account does not need to be a member of any repo/org (except during the initial setup). The deploy keys we use are repo-specific, meaning each of them can only push into a single repo--so even if the bot account had extended rights over an org or repo and one of the deploy keys was leaked, the deploy key could not be abused to push to any random repo.
When using a GitHub token, rather than a repo-specific deploy key, as far as I understand, the token _cannot_ be limited in its scope to only allow pushing to select repos (I think you can limit the number of things that can be done though, e.g. only write issue comments or such, but that's not going to help us).
