### ISSUE TITLE
Allow to ignore DC files in templates

### ISSUE THREAD

**Issue by tomschr** [openSUSE/doc-ci#36]
# Problem

Tanja and I would like to separate template files from real work (see issue SUSE/doc-modular#5). 

After I've separated the templates into a separate folder and created a substructure, the GHA CI finds them as well.

However, the GHA `openSUSE/doc-ci@gha-select-dcs` doesn't provide a parameter to ignore DC files. This could be necessary as everything we build is theoretically subject for publishing. To avoid to publish content that only serves as an example we need to distinguish such examples/templates from real content.

# Proposed solution

Not sure if we want to do a recursive search of a repo for all DC files. Maybe we should allow a finer grained selection of DC files. For example, we could introduce a `ignore-dc-files` parameter or anything similar. You pass DC files which need to be ignored. That would remove these files from being validated (and unwanted results published).

Unfortunately, a `on.push.paths-ignore` entry in the workflow file doesn't have an impact.

Affected files in branch `gha-select-dcs`
* `doc-ci/select-dcs.sh` to deal with the ignored files
* `action.yml` to provide this new parameter
* `Dockerfile` to pass the parameter to the shell script

**Comment by ghost** [comment]
The DC files are only being validated & I don't actually see an issue with that.

The selection of DC files to publish is different and depends on the config.xml from https://github.com/susedoc/susedoc.github.com/

I'd vote to close this one unless you disagree.

**Comment by tomschr** [comment]
Hmn, yes, the publish is different.

I still think it would be a nice & helpful addition, but for the time being it's probably not that important. We can reopen it if we need it.

Thanks.
